### PR TITLE
e-Migtaion-2

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
1. GitHub and Slack buttons are not aligned.

screen shot 2017-07-24 at 5 48 55 pm

2. Missing reading progress component on some pages under `Guides`

screen shot 2017-07-24 at 5 48 01 pm

Besides that, I think we should rethink all of our content. For example, the whole `Quick Start` tutorials could be converted to an actual step-by-step tutorial [like this](http://wedeploy.com/tutorials/hosting/get-started.html). But I like that we're moving this forward, good job @blzaugg!

**Comment by robframpton** [comment]
@zenorocha 

The idea was to first do a 1 to 1 migration of all the content and get it published. Then go rethink the structure and contents.

**Comment by zenorocha** [comment]
Nice! Totally makes sense ;)

**Comment by blzaugg** [comment]
@zenorocha, the missing reading progress was intentional, those are such short articles I didn't add any value. But it's trivial to add them back. I just need to change the layout prop.

**Comment by blzaugg** [comment]
I'll need to look into the icon alignment

**Comment by zenorocha** [comment]
I think it's good to have for consistency. It also gives you a glimpse of that page is about.

**Comment by blzaugg** [comment]
K, I'll change it back.

 - [x] GitHub and Slack buttons are not aligned.
 - [x] Missing reading progress component on some pages under `Guides`

**Comment by blzaugg** [comment]
@zenorocha, I'm not able to replicate the icon alignment. But I changed the way I align the icons. Please take a look.

https://github.com/metal/metaljs.com/pull/56

**Pull request closed without merging**
