### PR TITLE
Adds prepareStateForRender to the lifecycle documentation

### PR DESCRIPTION
**Pull request by fernandosouza**
cc @yuchi

### CODE REVIEW

**Review by brunobasto — COMMENTED** [review]
"and you can handle any necessary value you want before passing it down to the template"

I think it's good, but maybe we could make it just a bit more clear that this is the lifecycle method that gives the developer the `opportunity` to massage / prepare data for the templates.

**Comment by fernandosouza** [comment]
Doc updated, @brunobasto. Can you check if it's better?

**Comment by fernandosouza** [comment]
https://github.com/metal/metal.js/pull/181/files

**Review by brunobasto — APPROVED** [review]

**Comment by jbalsas** [comment]
Hey @fernandosouza, could you send this against the https://github.com/metal/metaljs.com/pull/54 branch? I'm afraid we might lose it if we merge to master now :/

**Comment by fernandosouza** [comment]
I'm closing this because it was already merged into master in another pull request.

**Pull request closed without merging**
