### PR TITLE
Documents metal/metal.js#267

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @mwilliams2014, this is also almost ready to go in... could you wordsmith it for us as well?

Thanks!

**Comment by mwilliams2014** [comment]
merged locally

**Comment by mwilliams2014** [comment]
sent https://github.com/metal/metaljs.com/pull/73

**Comment by jbalsas** [comment]
Closing in favor of #73

**Pull request closed without merging**
