### PR TITLE
Create index page for tutorials

### PR DESCRIPTION
**Pull request by robframpton**
Note: eventually we might add a different index page for tutorials to Electric, but until then I would like to have something so we can at least provide these tutorials.

screen shot 2017-12-04 at 10 21 39 am

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, this looks good for the most part, I just have some concerns with the navigation and the transition between tutorials and other guides. See attached gif:

tutorials

Things that bother me:
- The side bar has different widths so the page jumps right and left
- We lose all reference of where we are when we step inside a tutorial... maybe could we just devise a header with a back link, like `< Back to Documentation`?

**Comment by robframpton** [comment]
Hey @zenorocha,

Do you think we could change the tutorial sidebar width in Marble so that they match?

**Comment by robframpton** [comment]
I went ahead and made those changes on this project for now.

**Comment by zenorocha** [comment]
Awesome, thanks @Robert-Frampton. I'll also try to get a design for that page in January so we can have something more elaborated ;)

**Comment by jbalsas** [comment]
Looks good, @Robert-Frampton! There's still some jump in the header, font changes size from the regular pages to the tutorials. I'm merging this in, but please, take a look to see if it can be easily fixed.

header

**Pull request merged**
