### PR TITLE
Create soy path for todo tutorial

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by robframpton** [comment]
Note: before launching these tutorials we should create an index page for all tutorials. Right now marble doesn't have any templates for something like that, but @zenorocha has mentioned a desire to do so.

@zenorocha, any chance we can add an index page for tutorials to Electric/Marble?

**Comment by jbalsas** [comment]
Hey @Robert-Frampton, this looks great, I love that both tutorials have the same sections, it makes it very easy to reason with and map features and implementations together! 👏 

I just saw some visual glitches here and there:

* Topbar has logo and name stuck together and the Documentation link seems misaligned
screen shot 2017-11-28 at 10 09 02

* Missing styling for code language tabs in soy tutorial (`event-listeners`)
screen shot 2017-11-28 at 10 12 17

I'm seeing a JS error missing `moment` which might be the cause of some of this:
```javascript
pageIndex.js:1347 Uncaught Error: Cannot find module "moment"
    at webpackMissingModule (pageIndex.js:1347)
    at Object.defineProperty.value (pageIndex.js:1347)
    at __webpack_require__ (shared.electric.js:55)
    at Object.<anonymous> (pageIndex.js:11390)
    at __webpack_require__ (shared.electric.js:55)
    at webpackJsonpCallback (shared.electric.js:26)
    at pageIndex.js:2
```

**Comment by robframpton** [comment]
Hey @jbalsas,

All of those styling issues except for the code tabs one will be fixed if you reinstall the project's local dependencies.

The code tabs issue needs to be addressed in Marble eventually (/cc @zenorocha ), but I'll just add a workaround to this branch for now.

**Comment by jbalsas** [comment]
Merged!

@zenorocha, @mwilliams2014, double-check and send any followup you consider necessary!

**Pull request merged**
