### PR TITLE
Document lifecycle changes. Documents metal/metal.js#255

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by jbalsas** [comment]
I'm guessing this will need updating based on the new PR? https://github.com/metal/metal.js/pull/285

- Rename `willRender` to `willUpdate`
- Add `forceUpdate`

**Comment by jbalsas** [comment]
Also, what about some kind of Rosetta stone table like the one in https://github.com/metal/metal.js/issues/255#issuecomment-328067675?

**Comment by jbalsas** [comment]
@mwilliams2014, we are almost done with this as well, could you please take a look as well? Thanks!

**Comment by robframpton** [comment]
Since metal/metal.js#255 has received some small changes, I need to update this branch.

**Pull request merged**
